---
title: "PS811 Portfolio"
author: "Lisa de Sousa Dias"
output:
  html_document: 
    toc: true ## table of contents
    code_folding: hide
---
```{r setup, include=FALSE}
## Defaults for R chunks
knitr::opts_chunk$set(echo = TRUE, ## echo = TRUE means code will show
                      warning=FALSE, ## supress warnings and messages from R
                      message=FALSE,
                      fig.path='Figs/', ## where to save figures
                      fig.height = 3, ## default figure size (can differ in each chunk)
                      fig.width = 3)

## Add any R packages you require. 
## Here are some we will use in 811:
requires <- c("tidyverse", ## tidyverse includes dplyr and ggplot2
              "magrittr",
              "foreign",
              "readstata13",
              "here")

## Install any you don't have
to_install <- c(requires %in% rownames(installed.packages()) == FALSE)
install.packages(c(requires[to_install], "NA"), repos = "https://cloud.r-project.org/" )

## Load all required R packages
library(tidyverse)
library(ggplot2); theme_set(theme_minimal())
library(magrittr)
library(here)
```
<!-- The above header sets everything up. -->





<!-- Replace the below with bit about you. -->
### Research Interests

I am interested in nonviolent resistance and protest movements in sub-Sahran Africa. More specifically, I want to investigate the aftermath of protests and variation government responses and reforms. I am also interested in understanding the short and long-term consequences of violence and repression.  

### Questions I hope to answer
Do protest movements catalyze government reforms? What explains variation in how governments respond to protests? How does the use of state-sponspored violence and repression impact protest movements? 

---

### Methods
Mixed-methods. Process tracing, large-n statistical analysis, interviews, ethnogrpahy. 

---

### Relevent data
- The Social Conflict Analysis Database (SCAD) - ( [data](https://www.strausscenter.org/scad.html)]

- The Global Digital Activism Data Set (GDADS) - ( [data](https://www.icpsr.umich.edu/icpsrweb/ICPSR/studies/34625/datadocumentation))

- The Armed Conflict Location and Event Data Project (ACLED) - ( [data](https://www.acleddata.com/data/)]

- The GDELT Project - ( [data](https://www.gdeltproject.org/data.html))

<!--
Lisa, 
These datasets look like great options from which to select a few variables of interest. GDELT especially is massive, so you may want to write a separate R script that downloads your dataset of interest, selects a number of variables, and saves a smaller file in your data subfolder that this script can then call upon. 
Best,
Devin 
-->

---

